apiVersion: v1
kind: Service
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  ports:
    - port: 80
  selector:
    app: joomla
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
    env: test
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joomla
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joomla
        env: test
        tier: frontend
    spec:
      containers:
      - image: joomla:3.9.18-apache
        name: joomla
        env:
        - name: JOOMLA_DB_HOST
          value: joomla-mysql
        - name: JOOMLA_DB_PASSWORD
          value: "rootpasswd"
        ports:
        - containerPort: 80
          name: joomla
        volumeMounts:
        - name: task-pv-volume
          mountPath: /var/www/html
      volumes:
      - name: task-pv-volume
        persistentVolumeClaim:
          claimName: task-pv-claim
